name: Build and publish multi-arch Docker images

on:
  push:
    branches: [main]
  workflow_dispatch:  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Login to GHCR ---
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Login to Docker Hub ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Build mihomo ---
      - name: Read version for mihomo
        id: mihomo_version
        run: echo "VERSION=$(cat ./mihomo/VERSION)" >> $GITHUB_OUTPUT

      - name: Build and push mihomo
        uses: docker/build-push-action@v4
        with:
          context: ./mihomo
          file: ./mihomo/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mihomo/mihomo:latest
            ghcr.io/${{ github.repository_owner }}/mihomo/mihomo:${{ steps.mihomo_version.outputs.VERSION }}
            ${{ github.repository_owner }}/mihomo:latest
            ${{ github.repository_owner }}/mihomo:${{ steps.mihomo_version.outputs.VERSION }}

      # --- Build mihomo_env ---
      - name: Read version for mihomo_env
        id: mihomo_env_version
        run: echo "VERSION=$(cat ./mihomo_env/VERSION)" >> $GITHUB_OUTPUT

      - name: Build and push mihomo_env
        uses: docker/build-push-action@v4
        with:
          context: ./mihomo_env
          file: ./mihomo_env/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mihomo/mihomo_env:latest
            ghcr.io/${{ github.repository_owner }}/mihomo/mihomo_env:${{ steps.mihomo_env_version.outputs.VERSION }}
            ${{ github.repository_owner }}/mihomo_env:latest
            ${{ github.repository_owner }}/mihomo_env:${{ steps.mihomo_env_version.outputs.VERSION }}

      # # --- Cleanup old versions for mihomo ---
      # - name: Cleanup old GHCR versions (mihomo)
      #   uses: actions/delete-package-versions@v4
      #   with:
      #     package-name: 'magiasegura/mihomo'
      #     package-type: 'container'
      #     min-versions-to-keep: 5
      #     token: ${{ secrets.PACKAGE_TOKEN }}

      # # --- Cleanup old versions for mihomo_env ---
      # - name: Cleanup old GHCR versions (mihomo_env)
      #   uses: actions/delete-package-versions@v4
      #   with:
      #     package-name: 'magiasegura/mihomo_env'
      #     package-type: 'container'
      #     min-versions-to-keep: 5

      #     token: ${{ secrets.PACKAGE_TOKEN }}



