name: Build and publish multi-arch Docker images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push stupid_tun (multi-arch)
        uses: docker/build-push-action@v4
        with:
          context: ./stupid_tun
          file: ./stupid_tun/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/vanes32/mihomo/stupid_tun:latest

      - name: Build and push mihomo (multi-arch)
        uses: docker/build-push-action@v4
        with:
          context: ./mihomo
          file: ./mihomo/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/vanes32/mihomo/mihomo:latest
